# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: python-deep-learning-chatbot
spec:
  type: LoadBalancer
  selector:
    app: karoba-chatbot
  ports:
    - protocol: "TCP"
      port: 8888
